Remove all caching on SPARQL endpoints
RDFLib/prez pull request #112
Opened 2023-05-15 02:37 UTC by recalcitrantsupplant

Resolves #76. Not clear on how/why the cache appends the results between requests, and apparently only on certain endpoints. Removed until the behaviour is better understood, or an alternate caching solution is introduced.

Does not resolve #16 if multiple Prez flavours are set to the same SPARQL endpoint. 

For #16 presumably Prez should deduplicate where the queries are sent - I don't want to make further changes until all of the expected behaviour is specified, or a decision is made to remove the use of multiple SPARQL endpoints.

Draft PR until above is resolved.

2023-05-19 11:03 UTC, nicholascar requested changes
This PR seems to remove the caching from the SPARQL query endpoints but not the CONSTRUCT endpoints and seems even to _add_ cachibg to the `sparql_construct_non_async`.

Am I reading this right? Shouldn't it remove all caching?

2023-05-20 05:18 UTC, edmondchuc commented
Same question from me. Why is caching not removed for construct queries?

I think until we have a suitable cache invalidation strategy, we should remove all caching for now to ensure new data loaded into the data store is reflected in the responses of the Prez API.

2023-05-20 07:39 UTC, recalcitrantsupplant commented
There's two commits, the first removed all caching (my draft PR), the second, after our discussion added back in caching for endpoints that the sparql router doesn't use, as we didn't think there was any issue with these. I should have created a new PR to make things clearer. See https://github.com/RDFLib/prez/pull/112/files . (Looks like I did accidentally add caching to a non async endpoint too yes, this can be removed, but it's not used by the /sparql endpoint)

The short answer is the /sparql endpoint is the only endpoint that uses the sparql_query function, which now has caching removed. Every other endpoint in prez uses the other functions such as sparql_construct.

The long answer is I took the existing code and modified it minimally to get this working. I think we've conflated the http methods with the types of queries when we don't need to. I suspect we can refactor/condense the functions quite a bit and this would clarify things. E.g. I don't think we should need to choose the endpoint function based on whether it's a construct, select, ask query

2023-05-22 06:10 UTC, edmondchuc commented
Should we remove all caching until we have a way to invalidate the cache without having to restart the Prez server?

I did a small search on the codebase and it looks like the `sparql_construct` function is being used to generate the search results and listing endpoints.

2023-05-23 00:14 UTC, merged