object endpoint to find internal links for resources
RDFLib/prez pull request #145
Opened 2023-08-09 12:57 UTC by recalcitrantsupplant

2023-08-23 06:58 UTC, jamiefeiss requested changes
Tested locally, the `/profiles` endpoint doesn't return `prez:links`

2023-08-24 07:05 UTC, edmondchuc commented
Can confirm. I have the same issue as @jamiefeiss.

2023-08-24 07:39 UTC, recalcitrantsupplant commented
I have a fix coming, should be tomorrow.

2023-08-28 07:41 UTC, jamiefeiss requested changes
After some local testing, I've found two issues:

1. For a `skos:Concept` page, the `prez:endpointComponentURI` triple seems to be missing:

```turtle
aarr:chair a skos:Concept ;
    dcterms:identifier "aarr:chair"^^prez1:identifier ;
    dcterms:provenance "Developed for this Agent to Agent Roles vocabulary"@en ;
    rdfs:isDefinedBy <https://data.idnau.org/pid/vocab/aarr> ;
    skos:broader aarr:member ;
    skos:definition "The presiding officer of an assembly, meeting, committee, or board"@en ;
    skos:inScheme <https://data.idnau.org/pid/vocab/aarr> ;
    skos:prefLabel "Chair"@en ;
    skos:scopeNote "Organisation to Person relations" ;
    prez1:link "/v/vocab/vcb:aarr/aarr:chair" .
```

2. For a `skos:Collection` page,  a server error occurs: `AttributeError: 'list' object has no attribute 'name'`, which points to this line:

https://github.com/RDFLib/prez/blob/4d5a0ba0bdcae67323d2373fed655c2aa05e6697/prez/services/generate_profiles.py#L90

where the problem seems to be a missing class in the SPARQL query:
```sparql
VALUES ?class {}
```

2023-08-28 08:26 UTC, recalcitrantsupplant commented
Thanks Jamie I'll take a look.

On Mon, 28 Aug 2023, 17:41 Jamie Feiss, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> After some local testing, I've found two issues:
>
>    1. For a skos:Concept page, the prez:endpointComponentURI triple seems
>    to be missing:
>
> aarr:chair a skos:Concept ;
>     dcterms:identifier "aarr:chair"^^prez1:identifier ;
>     dcterms:provenance "Developed for this Agent to Agent Roles ***@***.*** ;
>     rdfs:isDefinedBy <https://data.idnau.org/pid/vocab/aarr> ;
>     skos:broader aarr:member ;
>     skos:definition "The presiding officer of an assembly, meeting, committee, or ***@***.*** ;
>     skos:inScheme <https://data.idnau.org/pid/vocab/aarr> ;
>     skos:prefLabel ***@***.*** ;
>     skos:scopeNote "Organisation to Person relations" ;
>     prez1:link "/v/vocab/vcb:aarr/aarr:chair" .
>
>
>    1. For a skos:Collection page, a server error occurs: AttributeError:
>    'list' object has no attribute 'name', which points to this line:
>
>
> https://github.com/RDFLib/prez/blob/4d5a0ba0bdcae67323d2373fed655c2aa05e6697/prez/services/generate_profiles.py#L90
>
> where the problem seems to be a missing class in the SPARQL query:
>
> VALUES ?class {}
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RDFLib/prez/pull/145#pullrequestreview-1597661411>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACQUSNXFSDPJY7PKTRKH4A3XXRDTVANCNFSM6AAAAAA3J63ICA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-29 07:21 UTC, recalcitrantsupplant commented
@jamiefeiss both fixed now - note I've switched to the dcterms:identifier to include parent URL components / their labels. From the updated notes:

_Add a triple: of the form: `<endpoint_component_uri> dcterms:identifier "{curie_id}"^^prez:identifier` for parent CURIEs in endpoints such that the URIs of parents are included in the response, and get annotated, such that labels are available for breadcrumbs._

2023-08-30 05:39 UTC, edmondchuc requested changes

2023-08-30 05:39 UTC, edmondchuc commented on prez/cache.py
> +profiles_graph_cache.bind("prez", "https://prez.dev/")
```suggestion
endpoints_graph_cache.bind("prez", "https://prez.dev/")
```

2023-08-30 06:01 UTC, recalcitrantsupplant commented on prez/cache.py
> +profiles_graph_cache.bind("prez", "https://prez.dev/")
I wonder if in future we change all of the system graphs to an RDFLib Dataset

2023-08-30 07:10 UTC, edmondchuc commented on prez/cache.py
> +profiles_graph_cache.bind("prez", "https://prez.dev/")
Yes we should migrate over soon. ConjunctiveGraph is marked for removal in a future release of RDFLib.

2023-08-30 07:16 UTC, jamiefeiss approved these changes
The frontend has everything it needs now after local testing. Thanks David

2023-08-30 09:47 UTC, recalcitrantsupplant commented
@edmondchuc I think I've addressed the feedback (just the single suggested change) let me know if I've missed something otherwise will merge

2023-08-31 05:07 UTC, jamiefeiss requested changes
I found another issue I must've overlooked before: search results are missing labels and geometries. See the screenshot below, the map with geometries should be displaying on the right:

![image](https://github.com/RDFLib/prez/assets/58060490/34e1753d-f1e6-4aeb-bb9b-5c7c0a68600d)

2023-08-31 07:59 UTC, recalcitrantsupplant commented
thanks Jamie, not sure if these changes caused that issue, in any case I'd like to merge this in before this PR gets any larger. Could you raise an issue separately? I'll address it when making the filter addition to search.

2023-08-31 08:00 UTC, merged