Profiles fixes
RDFLib/prez pull request #84
Opened 2023-04-13 04:09 UTC by recalcitrantsupplant

- removes unused code
- uses CURIEs as profile tokens

2023-04-13 04:36 UTC, edmondchuc requested changes

2023-04-13 04:36 UTC, edmondchuc commented on prez/app.py
> +    # await generate_support_graphs()
Should probably remove this

2023-04-13 04:37 UTC, edmondchuc commented
Just left a comment, otherwise looks good.

2023-04-13 06:22 UTC, jamiefeiss requested changes
Tested with the frontend, works fine except for a couple things:

- Profiles listed in /v/profiles, /s/profiles & /c/profiles returns links for each profile as /v/profile/<id>, etc rather than /profile/<id>
- The data for each individual profile still shows dcterms:identifier as the old token rather than the curie. Is that intended behaviour?

2023-04-13 10:50 UTC, recalcitrantsupplant commented
I don't see a conceptual issue with listing the profiles at both /profiles and under any subsystems they apply to. To me, I think it's more logical to direct a user who is already at say /v/profiles to a link that adds to that path. We also list objects at both /object and under endpoints, and collections in the case of spaceprez will be at both /collections and /datasets/<ds>/collections. If this isn't causing any technical issues let's perhaps move it to a discussion and close the pr. 

Similarly for the identifiers, they don't serve any technical/system requirement now, so I think it's more a case of do they serve any other purpose. To be clear, we are not saying the dcterms:identifier is now the curie; rather the prez system identifier (only used for the URL paths and header links) is the curie. Prez now treats dcterms identifiers like any other property.

@jamiefeiss could you confirm re whether there's any system issues and we can close this/probably just discuss on signal

2023-04-14 04:34 UTC, edmondchuc approved these changes

2023-04-14 05:08 UTC, merged